# Generated by Django 5.2.5 on 2025-09-06 02:58

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumbradoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('LED', 'LED'), ('SOLAR', 'Solar')], max_length=50)),
                ('estado', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('DAÑADO', 'Dañado'), ('APAGADO', 'Apagado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='FUNCIONANDO', max_length=20)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alumbrado Público',
                'verbose_name_plural': 'Alumbrado Público',
                'ordering': ['tipo', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('comuna', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cuadrante', models.CharField(blank=True, max_length=10, null=True)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_m2', models.FloatField(blank=True, help_text='Área en metros cuadrados', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstacionPolicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('CAI', 'Centro de Atención Inmediata'), ('ESTACION', 'Estación de Policía'), ('SUBESTACION', 'Subestación de Policía'), ('PUESTO', 'Puesto de Policía')], max_length=50)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cobertura_geometria', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Estación de Policía',
                'verbose_name_plural': 'Estaciones de Policía',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Homicidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caso', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('dia_de_semana', models.CharField(blank=True, max_length=20)),
                ('tipo_violencia', models.CharField(blank=True, max_length=100)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lugar_hechos', models.CharField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('modalidad', models.CharField(blank=True, max_length=100)),
                ('arma_utilizada', models.CharField(blank=True, max_length=50)),
                ('genero_victima', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('edad_victima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('resumen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.barrio')),
            ],
            options={
                'verbose_name': 'Homicidio',
                'verbose_name_plural': 'Homicidios',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
